name: Checkin Workflow

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'  # UTC时间4点，北京时间中午12点

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run checkin script
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          python -c "
          import requests
          headers = {'Authorization': '$AUTH_TOKEN'}
          response = requests.get('https://www.aibvs.net/api/user/checkin', headers=headers)
          print(response.status_code)
          print(response.text)
          "
