name: Checkin Workflow

on:
  schedule:
    - cron:  '0 4 * * *'  # UTC时间4点，北京时间中午12点
  workflow_dispatch:  # 手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
          
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: '1135580'

#       - name: Set up ChromeDriver
#         uses: nanasess/setup-chromedriver@v2
#         with:
#           chromedriver-version: '114.0.5735.90'
      
      - name: Install dependencies
        run: |
          pip install selenium==3.8.0

      - name: generate config.ini
        run:
          python3 actions.py -u ${{ secrets.EMAIL1 }} -p ${{ secrets.PASSWD1 }}

      - name: main
        run:
          python3 main.py

      - name: generate config.ini
        run:
          python3 actions.py -u ${{ secrets.EMAIL2 }} -p ${{ secrets.PASSWD2 }}
      
      - name: main
        run:
          python3 main.py

      # - name: generate config.ini
      #   run:
      #     python3 actions.py -u ${{ secrets.EMAIL3 }} -p ${{ secrets.PASSWD3 }}
      
      # - name: main
      #   run:
      #     python3 main.py
