name: Checkin Workflow

on:
  schedule:
    - cron:  '0 4 * * *'  # UTC时间4点，北京时间中午12点
  workflow_dispatch:  # 手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          pip install selenium==3.8.0

      - name: Test chromedriver
        run: |
          chromedriver --version

      - name: Prepare chromedriver
        uses: nanasess/setup-chromedriver@v2

      - name: Working
        run: |
          python3 actions.py -u ${{ secrets.EMAIL1 }} -p ${{ secrets.PASSWD1 }}
          python3 main.py
          python3 actions.py -u ${{ secrets.EMAIL2 }} -p ${{ secrets.PASSWD2 }}
          python3 main.py
